const productData = [
  {
    id: 1,
    name: "Coca-Cola",
    slug: "coca-cola",
    brand: "Coca-Cola Company",
    category: "Beverages",
    price: 1.5,
    discount: 10,
    availability_status: "In Stock",
    return_policy: "7-day return",
    weight: "500ml",
    dimensions: "6x6x20 cm",
    shipping_cost: 2.0,
    tags: ["soft drink", "carbonated", "beverage"],
    thumbnail: "/thumbnails/coca_cola.jpg",
    image: "/ca1.jpg",
    warranty_information: "No warranty",
    color: "Red",
    rating: 5,
    createdAt: "2024-12-20T08:00:00Z",
    authorName: "John Doe",
    authorImage: "/images/author1.jpg",
  },
  {
    id: 2,
    name: "Orange Juice",
    slug: "orange-juice",
    brand: "Tropicana",
    category: "Beverages",
    price: 2.0,
    discount: 15,
    availability_status: "In Stock",
    return_policy: "5-day return",
    weight: "1L",
    dimensions: "8x8x25 cm",
    shipping_cost: 3.0,
    tags: ["juice", "citrus", "natural"],
    thumbnail: "/thumbnails/orange_juice.jpg",
    image: "/ca2.jpg",
    warranty_information: "No warranty",
    color: "Orange",
    rating: 4,
    createdAt: "2024-12-19T10:00:00Z",
    authorName: "Jane Smith",
    authorImage: "/images/author2.jpg",
  },
  {
    id: 3,
    name: "Salted Butter",
    slug: "salted-butter",
    brand: "Lurpak",
    category: "Butter & Eggs",
    price: 3.0,
    discount: 5,
    availability_status: "In Stock",
    return_policy: "Non-returnable",
    weight: "250g",
    dimensions: "10x5x3 cm",
    shipping_cost: 1.5,
    tags: ["butter", "dairy", "salted"],
    thumbnail: "/thumbnails/salted_butter.jpg",
    image: "/ca3.jpg",
    warranty_information: "No warranty",
    color: "Yellow",
    rating: 4,
    createdAt: "2024-12-18T09:00:00Z",
    authorName: "Mark Johnson",
    authorImage: "/images/author3.jpg",
  },
  {
    id: 4,
    name: "Free-Range Eggs (12 pack)",
    slug: "free-range-eggs-12-pack",
    brand: "Organic Valley",
    category: "Butter & Eggs",
    price: 4.0,
    discount: 8,
    availability_status: "In Stock",
    return_policy: "Non-returnable",
    weight: "12 eggs",
    dimensions: "20x10x6 cm",
    shipping_cost: 2.5,
    tags: ["eggs", "organic", "free-range"],
    thumbnail: "/thumbnails/eggs_pack.jpg",
    image: "/ca4.jpg",
    warranty_information: "No warranty",
    color: "White",
    rating: 4,
    createdAt: "2024-12-17T11:00:00Z",
    authorName: "Alice Brown",
    authorImage: "/images/author4.jpg",
  },
  {
    id: 5,
    name: "Pasta",
    slug: "pasta",
    brand: "Barilla",
    category: "Dried Food",
    price: 1.2,
    discount: 10,
    availability_status: "In Stock",
    return_policy: "14-day return",
    weight: "500g",
    dimensions: "25x10x5 cm",
    shipping_cost: 1.0,
    tags: ["pasta", "dry food", "italian"],
    thumbnail: "/thumbnails/pasta.jpg",
    image: "/ca5.jpg",
    warranty_information: "No warranty",
    color: "Yellow",
    rating: 4,
    createdAt: "2024-12-16T12:00:00Z",
    authorName: "David White",
    authorImage: "/images/author5.jpg",
  },
  {
    id: 6,
    name: "Rice",
    slug: "rice",
    brand: "Basmati",
    category: "Dried Food",
    price: 0.8,
    discount: 12,
    availability_status: "In Stock",
    return_policy: "14-day return",
    weight: "1kg",
    dimensions: "20x15x5 cm",
    shipping_cost: 2.0,
    tags: ["rice", "grains", "staple food"],
    thumbnail: "/thumbnails/rice.jpg",
    image: "/ca1.jpg",
    warranty_information: "No warranty",
    color: "White",
    rating: 5,
    createdAt: "2024-12-15T13:00:00Z",
    authorName: "Eve Green",
    authorImage: "/images/author6.jpg",
  },
  {
    id: 7,
    name: "Chicken Breast",
    slug: "chicken-breast",
    brand: "FreshFarm",
    category: "Fresh Meat",
    price: 5.5,
    discount: 5,
    availability_status: "In Stock",
    return_policy: "Non-returnable",
    weight: "500g",
    dimensions: "15x10x5 cm",
    shipping_cost: 3.0,
    tags: ["chicken", "fresh", "protein"],
    thumbnail: "/thumbnails/chicken_breast.jpg",
    image: "/ca2.jpg",
    warranty_information: "No warranty",
    color: "Pink",
    rating: 5,
    createdAt: "2024-12-14T14:00:00Z",
    authorName: "Henry Black",
    authorImage: "/images/author7.jpg",
  },
  {
    id: 8,
    name: "Ground Beef",
    slug: "ground-beef",
    brand: "Butcher's Choice",
    category: "Fresh Meat",
    price: 6.0,
    discount: 8,
    availability_status: "In Stock",
    return_policy: "Non-returnable",
    weight: "500g",
    dimensions: "15x10x5 cm",
    shipping_cost: 3.0,
    tags: ["beef", "meat", "fresh"],
    thumbnail: "/thumbnails/ground_beef.jpg",
    image: "/ca3.jpg",
    warranty_information: "No warranty",
    color: "Red",
    rating: 4,
    createdAt: "2024-12-13T15:00:00Z",
    authorName: "Olivia Gray",
    authorImage: "/images/author8.jpg",
  },
  {
    id: 9,
    name: "Bananas",
    slug: "bananas",
    brand: "Dole",
    category: "Fruits",
    price: 1.1,
    discount: 0,
    availability_status: "In Stock",
    return_policy: "Non-returnable",
    weight: "1kg",
    dimensions: "20x15x10 cm",
    shipping_cost: 1.0,
    tags: ["fruit", "banana", "fresh"],
    thumbnail: "/thumbnails/bananas.jpg",
    image: "/ca4.jpg",
    warranty_information: "No warranty",
    color: "Yellow",
    rating: 3,
    createdAt: "2024-12-12T16:00:00Z",
    authorName: "Sophia Lee",
    authorImage: "/images/author9.jpg",
  },
  {
    id: 10,
    name: "Apples",
    slug: "apples",
    brand: "Honeycrisp",
    category: "Fruits",
    price: 2.5,
    discount: 5,
    availability_status: "In Stock",
    return_policy: "Non-returnable",
    weight: "1kg",
    dimensions: "15x15x10 cm",
    shipping_cost: 2.0,
    tags: ["fruit", "apple", "fresh"],
    thumbnail: "/thumbnails/apples.jpg",
    image: "/ca5.jpg",
    warranty_information: "No warranty",
    color: "Red",
    rating: 4,
    createdAt: "2024-12-11T17:00:00Z",
    authorName: "Lucas Harris",
    authorImage: "/images/author10.jpg",
  },
  {
    id: 11,
    name: "Carrots",
    slug: "carrots",
    brand: "Fresh Farm",
    category: "Vegetables",
    price: 0.9,
    discount: 8,
    availability_status: "In Stock",
    return_policy: "Non-returnable",
    weight: "1kg",
    dimensions: "15x10x10 cm",
    shipping_cost: 1.0,
    tags: ["vegetables", "carrot", "organic"],
    thumbnail: "/thumbnails/carrots.jpg",
    image: "/ca1.jpg",
    warranty_information: "No warranty",
    color: "Orange",
    rating: 3,
    createdAt: "2024-12-10T18:00:00Z",
    authorName: "Liam Scott",
    authorImage: "/images/author11.jpg",
  },
  {
    id: 12,
    name: "Broccoli",
    slug: "broccoli",
    brand: "Green World",
    category: "Vegetables",
    price: 1.3,
    discount: 0,
    availability_status: "In Stock",
    return_policy: "Non-returnable",
    weight: "500g",
    dimensions: "15x15x10 cm",
    shipping_cost: 1.5,
    tags: ["vegetables", "broccoli", "organic"],
    thumbnail: "/thumbnails/broccoli.jpg",
    image: "/ca2.jpg",
    warranty_information: "No warranty",
    color: "Green",
    rating: 4,
    createdAt: "2024-12-09T19:00:00Z",
    authorName: "Mia Clark",
    authorImage: "/images/author12.jpg",
  },
];

export default productData;
